#!/bin/bash

# Script de Ejemplo: Flujo Completo de Versionamiento
# Demuestra cómo usar el versionamiento y rollback en Kubernetes

set -e

# Colores
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║  Ejemplo de Flujo de Versionamiento y Rollback          ║${NC}"
echo -e "${CYAN}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${YELLOW}Este es un ejemplo de cómo funciona el versionamiento.${NC}"
echo -e "${YELLOW}NO ejecutes este script directamente.${NC}"
echo ""
echo "Presiona Ctrl+C para cancelar o Enter para ver el ejemplo..."
read

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Paso 1: Crear versión 1.0.1${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${CYAN}# Editar el código${NC}"
echo "vim backend/server.js"
echo "# Agregar: // docs: cambio para versión 1.0.1"
echo ""
echo -e "${CYAN}# Construir y subir${NC}"
echo "./build-and-push.sh 1.0.1"
echo ""
echo -e "${CYAN}# Actualizar en Kubernetes${NC}"
echo "kubectl set image deployment/backend backend=wvarg/todo-backend:1.0.1 -n todo-app"
echo ""
echo -e "${CYAN}# Verificar el rollout${NC}"
echo "kubectl rollout status deployment backend -n todo-app"
echo ""
read -p "Presiona Enter para continuar..."

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Paso 2: Crear versión 1.0.2${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${CYAN}# Editar el código${NC}"
echo "vim backend/server.js"
echo "# Agregar: // docs: cambio para versión 1.0.2"
echo ""
echo -e "${CYAN}# Construir y subir${NC}"
echo "./build-and-push.sh 1.0.2"
echo ""
echo -e "${CYAN}# Actualizar en Kubernetes${NC}"
echo "kubectl set image deployment/backend backend=wvarg/todo-backend:1.0.2 -n todo-app"
echo ""
read -p "Presiona Enter para continuar..."

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Paso 3: Crear versión 1.0.3${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${CYAN}# Editar el código${NC}"
echo "vim backend/server.js"
echo "# Agregar: // docs: cambio para versión 1.0.3"
echo ""
echo -e "${CYAN}# Construir y subir${NC}"
echo "./build-and-push.sh 1.0.3"
echo ""
echo -e "${CYAN}# Actualizar en Kubernetes${NC}"
echo "kubectl set image deployment/backend backend=wvarg/todo-backend:1.0.3 -n todo-app"
echo ""
read -p "Presiona Enter para continuar..."

echo ""
echo -e "${YELLOW}═══════════════════════════════════════════════════════${NC}"
echo -e "${YELLOW}¡Oh no! La versión 1.0.3 tiene un bug...${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════${NC}"
echo ""
read -p "Presiona Enter para hacer rollback..."

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Paso 4: Rollback a versión anterior (1.0.2)${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${CYAN}# Opción A: Rollback a la versión anterior${NC}"
echo "kubectl rollout undo deployment backend -n todo-app"
echo ""
echo -e "${CYAN}# Opción B: Rollback a versión específica${NC}"
echo "kubectl set image deployment/backend backend=wvarg/todo-backend:1.0.2 -n todo-app"
echo ""
echo -e "${CYAN}# Verificar el rollback${NC}"
echo "kubectl rollout status deployment backend -n todo-app"
echo ""
echo -e "${CYAN}# Ver qué versión está corriendo${NC}"
echo "kubectl get deployment backend -n todo-app -o jsonpath='{.spec.template.spec.containers[0].image}'"
echo ""
read -p "Presiona Enter para continuar..."

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Paso 5: Ver historial de versiones${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${CYAN}# Ver historial de deployments${NC}"
echo "kubectl rollout history deployment backend -n todo-app"
echo ""
echo -e "${CYAN}# Ver detalles de una revisión específica${NC}"
echo "kubectl rollout history deployment backend -n todo-app --revision=2"
echo ""
echo -e "${CYAN}# Ver versiones en Docker Hub${NC}"
echo "docker images wvarg/todo-backend"
echo ""
echo -e "${CYAN}# Ver log de versiones${NC}"
echo "cat version-history.log"
echo ""

echo ""
echo -e "${CYAN}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║  ✓ Ejemplo Completo                                     ║${NC}"
echo -e "${CYAN}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GREEN}Resumen del flujo:${NC}"
echo "  1. Crear versión 1.0.1 con ./build-and-push.sh 1.0.1"
echo "  2. Desplegar con kubectl set image"
echo "  3. Crear versión 1.0.2"
echo "  4. Crear versión 1.0.3"
echo "  5. Si hay problema, hacer rollback"
echo ""
echo -e "${YELLOW}Para más información:${NC}"
echo "  cat GUIA-VERSIONAMIENTO.md"
echo ""
