---
# ConfigMap con variables de configuración
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: todo-app
data:
  # MongoDB
  MONGODB_HOST: "mongodb-service"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "tododb"
  
  # Redis
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Backend
  BACKEND_PORT: "5000"
  NODE_ENV: "production"
  
  # Frontend
  REACT_APP_API_URL: "http://localhost:5000"

---
# Secret para credenciales sensibles
apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: todo-app
type: Opaque
stringData:
  mongodb-username: "admin"
  mongodb-password: "securepassword123"
  mongodb-root-password: "rootpassword123"
  redis-password: ""  # Sin password para desarrollo
