---
# Worker Deployment para K3D
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: todo-app
  labels:
    app: worker
    component: background
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        component: background
    spec:
      initContainers:
      - name: wait-for-mongodb
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          until nc -z mongodb-service 27017; do
            echo "Esperando MongoDB..."
            sleep 2
          done
      - name: wait-for-redis
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          until nc -z redis-service 6379; do
            echo "Esperando Redis..."
            sleep 2
          done
      containers:
      - name: worker
        image: todo-worker:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGODB_URI
          value: "mongodb://admin:securepassword123@mongodb-service:27017/tododb?authSource=admin"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          exec:
            command:
            - pgrep
            - -f
            - node
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pgrep
            - -f
            - node
          initialDelaySeconds: 10
          periodSeconds: 5
