---
# ConfigMap para la configuración de Nginx en K3D
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: todo-app
data:
  default.conf: |
    upstream backend_api {
        # Balanceo de carga - Kubernetes DNS
        least_conn;
        server backend-service.todo-app.svc.cluster.local:5000 max_fails=3 fail_timeout=30s;
    }

    upstream frontend_app {
        server frontend-service.todo-app.svc.cluster.local:80;
    }

    # Servidor principal
    server {
        listen 80;
        server_name localhost;
        
        # Logs
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log warn;

        # Configuración de timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        # Headers de seguridad
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;

        # Ruta para el frontend
        location / {
            proxy_pass http://frontend_app;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }

        # Ruta para la API
        location /api {
            proxy_pass http://backend_api;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Health check endpoint
        location /health {
            proxy_pass http://backend_api/health;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
        }

        # Configuración de caché para activos estáticos
        location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
            proxy_pass http://frontend_app;
            expires 7d;
            add_header Cache-Control "public, immutable";
        }
    }
